### ISSUE TITLE
node.docker portforwards are duplicated

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays_jumpscale8#11]
Having two instances of node.docker services consuming a node.ovc instance will have the same portforwards, which produces an error of ports already being allocated

**Comment by xmonader** [comment]
The problem is caused by the test_jumpscale_main service as it creates 2 node.docker with the same portforwards without mapping it explicitly.

**Comment by zaibon** [comment]
We can't close this. The bug is still there. If we don't map explicitly the port then AYS need to find free port and make the port forward properly.

**Comment by zaibon** [comment]
fixed in : https://github.com/Jumpscale/ays_jumpscale8/pull/24
