### ISSUE TITLE
mvp-cockpit: how to create with js a new Docker container on VM with Docker installed

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#112]
What is the recommended JumpScale code to create a new Docker container on a remote VM where Docker was installed using the app_docker actor?

What I did was the following:
```
[11]: ex = j.tools.executor.getSSHBased('172.98.207.206', 7122, 'cloudscalers', '8Udy1i1iP')
[12]: cuisine = j.tools.cuisine.get(ex)
[13]: cuisine.core.set_sudomode()
[14]: cuisine.development.js8.install()
[15]: dockerCuisineObj = cuisine.systemservices.docker.dockerStart(name='webdav', image='visity/webdav')
```

While this did do the job, there should be a better way, especially because step [14] takes like 10 minutes...

**Is there a way to get this done without having to install JS on the remote machine?**

**Comment by xmonader** [comment]
app_docker enables docker/dockercompose on the node that all  you need

```yaml
app_docker__ap:
    os: NAMEOF_OS_SSH_UBUNTU of the node.ovc
```

**Comment by yveskerwyn** [comment]
Yes I know, but that is not the question

**Comment by yveskerwyn** [comment]
The question is: How to do that using JumpScale code, through Cuisine?

**Comment by yveskerwyn** [comment]
Reply from @zaibon :

ok so the official supported way  is indeed installing jumpscale on the remote host
but like you I had this, it takes too much time and I don't find it optimal
so what I do:
I make the remote docker machine listening on a port
and then on my local machine I set the DOCKER_HOST variable
so the docker sal connects to the remote host directly

remote machine is an ubuntu 16.04 ? > yes

on the remote host I start docker with this option
/usr/bin/docker daemon -H tcp://172.20.0.1:4243
the -H makes docker listen on the public address of the machine
so I can connect to it remotely

this is not extremely secure though
because anyone can connect to it then

but don't know what's your use case here
but all this what I say here is valid for development only

we don't do all this shebang in AYS

too much manual steps

and not secure
