### ISSUE TITLE
revise AYS actors to match changes in 8.2.0

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays_jumpscale8#140]
check changes in dirs, changes in cuisine, changes in installer functions....

**Comment by rkhamis** [comment]
all previous blueprints should be working.
Check with QA for their testing blueprints and run.

**Comment by ashraffouda** [comment]
Tested 
1- g8client
2- vdc
3- node.ovc
4- os.ssh.ubuntu
5- sshkey
6- autosnapshotting

**Comment by rkhamis** [comment]
sshkey is missing a lot of logic.
Please revise

**Comment by ashraffouda** [comment]
tested 
1- sshkey > updated
2- g8osfs
