### ISSUE TITLE
S3 actor documentation needs to be updated

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#145]
See schema:
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.0/templates/app/s3/schema.hrd

See (outdated) README:
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.0/templates/app/s3/REAME.md

**Comment by john-kheir** [comment]
Verified on 8.1.1
