### ISSUE TITLE
blueowncloud Actor README documentation needs update

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#148]
README:
https://github.com/Jumpscale/ays_jumpscale8/tree/master/templates/app/blueowncloud

Schema:
https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/app/blueowncloud/schema.hrd

**Comment by rkhamis** [comment]
https://github.com/Jumpscale/ays_jumpscale8/tree/8.2.0/templates/app/blueowncloud
