### ISSUE TITLE
vdc Actor needs support to set the external network

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#149]
Proposed schema addition:
`externalNetwork = type:int list:1:1`

**Comment by grimpy** [comment]
PLease fix as PR on 8.1.1

**Comment by john-kheir** [comment]
this ticket is blocked by: https://github.com/0-complexity/openvcloud/issues/725

**Comment by rkhamis** [comment]
0-complexity/openvcloud#725 is on verification.

**Comment by john-kheir** [comment]
verified on 8.1.1
