### ISSUE TITLE
os.cockpit grafana action is broken

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays_jumpscale8#15]
cockpit client no longer exists
check https://github.com/Jumpscale/ays_jumpscale8/blob/master/_os/os.cockpit/actions.py#L85

**Comment by zaibon** [comment]
Indeed cockpit client has been removed cause all code related to cockpit is now in the github.com/Jumpscale/jscockpit/ repository.
We should probably store the grafana template somewhere else.

**Comment by zaibon** [comment]
Templates has been put back in https://github.com/Jumpscale/jscockpit
see https://github.com/Jumpscale/jscockpit/commit/e1b5ed48d09a89dba8fdd4e008ac2d3a9476be2d
