### ISSUE TITLE
automated testing for adding/removing vdc user access 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#154]
In order to avoid bugs like #153 we need automatic testing for adding/removing user access to a vdc

**Comment by yveskerwyn** [comment]
Also add:
- remove user
- add another user

Make sure to both test for existing and new users

**Comment by rkhamis** [comment]
@ramezsaeed should I move this to https://github.com/Jumpscale/ays_automatic_cockpit_based_testing/?

**Comment by ramezsaeed** [comment]
@rkhamis yes please move it

**Comment by rkhamis** [comment]
Moved to https://github.com/Jumpscale/ays_automatic_cockpit_based_testing/issues/26
