### ISSUE TITLE
Get rid of vdcfarm

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#156]
What is it for?

Please document: https://github.com/Jumpscale/ays_jumpscale8/issues/155

If no purpose, please remove

**Comment by xmonader** [comment]
It's used just for logical grouping (like you can have a farm of vms for databases)

**Comment by rkhamis** [comment]
Yes, it's a logical parent.
I'd prefer to keep it

**Comment by yveskerwyn** [comment]
OK
