### ISSUE TITLE
S3 actor parameter limits documentation

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#157]
What are valid values for the `key.access` and `key.secret`?

- large / small letters
- alphanumeric / complete character set / space
- minimum and maximum length

Do check this in the Actor and what error message will return?

Please update documentation:
https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/app/s3/REAME.md

**Comment by xmonader** [comment]
Those values are set on the data model after successfull installation of s3

**Comment by yveskerwyn** [comment]
The value can also be set before creation, so not just after successful installation

Question is, what are the allowed values, independent of when they are set

And do we check/validate them when setting the values through the Actor?

**Comment by xmonader** [comment]
12 characters from all letters + numbers from 0 to 9
https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/app/scality/actions.py#L33

And no, no validation for that.
