### ISSUE TITLE
Missing information in the autosnapshotting actor template documentation

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#158]
Currently the `snapshotInterval` is set per **hour**.

Needs to be documented in the [README.md](https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/autosnapshotting/README.md)

**Question**: can we also set `snapshotInterval` is set per **minute**?

**Comment by xmonader** [comment]
Well, all of those `duration` values are converted to seconds 
https://github.com/Jumpscale/jumpscale_core8/blob/master/lib/JumpScale/data/types/CustomTypes.py#L220

So, theoretically speaking, It should work if you change `1h` to `50m`.
