### ISSUE TITLE
Add auto to the g8client attribute in the uservdc actor template

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#162]
In order to make the [uservdc](https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/uservdc/schema.hrd) actor template schema consistent with the [vdc](https://github.com/Jumpscale/ays_jumpscale8/blob/master/templates/ovc/vdc/schema.hrd) actor template schema, add `auto` to the `g8client` attribute:

So change:
`g8client = type:str consume:'g8client'`
 to:
`g8client = type:str consume:'g8client' auto`

**Comment by xmonader** [comment]
https://github.com/Jumpscale/ays9/commit/8f19735100517d255d68634afc4ec5ea79770b0d
