### ISSUE TITLE
Remove allowedVMSizes from the vdc actor template

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#168]
Since we already have `maxMemoryCapacity`,`maxCPUCapacity` and `maxDiskCapacity` there is no need to set a limit on the (allowed) combinations (sizes).

While the VDC Control Panel allows you to choose any of the packages (number of vCPU core + memory) and any of the (boot) disk sizes when creating a new VM, you'll get an error if the chosen combination cannot be provisioned because you hit the limits set for the cloud space with the other limits.

**Comment by john-kheir** [comment]
Verified on 8.1.1
