### ISSUE TITLE
Maximum autoscale capacity for S3 and owncloud is not implemented

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/ays_jumpscale8#171]
The autoscale functionality need to have a configurable limit where u set that u don't want to scale up above a certain size.

**Comment by rkhamis** [comment]
@yveskerwyn @muhamadazmy I don't feel this is a blocking issue on 8.1.1.
What do you guys think?

**Comment by yveskerwyn** [comment]
Not for me no

**Comment by rkhamis** [comment]
Will set it on 8.2.0/8.2.1

**Comment by rkhamis** [comment]
Moved to https://github.com/Jumpscale/ays9/issues/3

**Comment by xmonader** [comment]
https://github.com/Jumpscale/ays9/commit/5b9dbe9ceef5c3f6bbd40811a2a359ebfbe27042
