### ISSUE TITLE
Install action fix in node.ovc breaks all blueprints where sizeID is not set, default=0

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#175]
This [fix](https://github.com/Jumpscale/ays_jumpscale8/commit/8affd4bf20a8ffe55ebc66d1ed29fbad2d1ed3be) breaks the [ovc.node Actor Template](https://github.com/Jumpscale/ays_jumpscale8/tree/8.1.1/templates/nodes/node.ovc) since [the default value for sizeID=0](https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.1/templates/nodes/node.ovc/schema.hrd):

When executing any blueprint using the ovc.node blueprint you will get this:

![screen shot 2017-02-15 at 09 56 35](https://cloud.githubusercontent.com/assets/13795109/22968373/718f7098-f36a-11e6-8f54-0561e3b85741.png)

**Comment by john-kheir** [comment]
verified on 8.1.1
