### ISSUE TITLE
S3 actor fails on creating VM

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#177]
See repository: https://lci.aydo2.com/ays81/Runs?repo=/optvar/cockpit_repos/yves1

The S3 actor creates in step 2 a new VDC, and goes after a while to step 3, creating the VM.

In step 2 it fails with the error `Could not get IP Address for machine s3server ((type:runtime.error)`.

Root cause is that the VDC did take too long to get created...

We should not go to step 2 until the VFW got created, this is not checked currently.

Second problem is that when starting a new run, when the cloud space got created successfully, the VM creating still fails... 

Also see the job details:

https://ma-g8-1.demo.greenitglobe.com/grid/job?id=f8fc9a116a7b424f96e9dc99c5edbb58

![screen shot 2017-02-16 at 09 02 33](https://cloud.githubusercontent.com/assets/13795109/23012461/b285c856-f426-11e6-82d9-55876979ff2e.png)

![screen shot 2017-02-16 at 09 02 40](https://cloud.githubusercontent.com/assets/13795109/23012470/b66ca408-f426-11e6-999b-8078ec707f9e.png)

**Comment by ashraffouda** [comment]
this cockpit is running old version 8.1.0, it is working in 8.1.1
also it runs actor form ays_jumpscale form master which is wrong

**Comment by yveskerwyn** [comment]
OK so I stop again using the cockpit in Production Mode, please add IYO integration to the "development version"...

**Comment by rkhamis** [comment]
Created a doc task for how to set dev mode here: https://github.com/Jumpscale/jscockpit/issues/372
