### ISSUE TITLE
VDC actor to manage adding external network

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#178]
Consuming the OpenvCloud API: POST /cloudbroker/iaas/addExternalNetwork

![screen shot 2017-02-20 at 18 32 43](https://cloud.githubusercontent.com/assets/13795109/23136008/01a86642-f79b-11e6-8e1a-cdfdece78000.png)

**Comment by rkhamis** [comment]
I think it would be better if we do it in the vdc template.
Should be handled in the install and update of the vdc.

**Comment by rkhamis** [comment]
Moved to https://github.com/Jumpscale/ays9/issues/4

**Comment by ashraffouda** [comment]
I think this is not related to vdc should be in a separate actor

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/ays9/commit/0a97769e44e6be613ec3c637a4db3dd8301d72e0
