### ISSUE TITLE
Does the S3 actor template accept 1 GB as the initial disk size?

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#182]
The [S3 "umbrella" actor template](https://github.com/Jumpscale/ays_jumpscale8/tree/8.1.1/templates/app/s3) takes a list of `disk.ovc` items as input, allowing you for instance to specify one disk of 1 GB (value=1000).

Given that autoscaling works in steps of 1 TB, will the autoscale feature step to 1001 (GB) if you specify 1 (GB) as the value for {size}?

If not, what is the minimal value?

```
...
disk.ovc__{disk-name}:
  size: {size}

s3__{s3server}:
  vdc: {vdc-name}
  sshkey: '{sshkey-name}''
  disk:
    - '{disk-name}'
...
```

**Comment by muhamadazmy** [comment]
That is indeed the case, the initial provided disk size doesn't have a minimum so a customer can specify a disk size of 1GB. Auto scaling will still add 1TB disks when needed.

**Comment by yveskerwyn** [comment]
thanks @muhamadazmy 

Do we step in 1024 GB or 1000 GB?

**Comment by muhamadazmy** [comment]
The default increment size is 1000GB, but it's configurable in the btrfs template

the fs.btrfs template has `incrementSize` attribute which defaults to 1000GB but can be changed in the blueprint to the value u want.
