### ISSUE TITLE
Configure cockpit to work with itsyouonline doesn't work

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#198]
**Description**
I installed cockpit 8.1.1 in a development mode then I followed these instructions 
https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/prep/Itsyou.online/configuration.md
to allow the login using itsyouonline

**Steps**
- Install cockpit machine in the development mode using the Installers
- Follow steps in the above readme to configure itsyou online.

**Actual result**
![screenshot from 2017-03-13 16-11-00](https://cloud.githubusercontent.com/assets/17981089/23857999/d3d5bb02-0807-11e7-8c57-dd9d697f5c83.png)

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/prep/Itsyou.online/configuration.md

**Comment by islamTaha12** [comment]
Please, Indicate that user have to use 'http' as a default in the following settings .. as https is required a ssl. 

**Set param.cfg.redirect_url = 'https://{cockpit-base-address}/restmachine/system/oauth/authorize'**

**Comment by yveskerwyn** [comment]
Updated: https://github.com/Jumpscale/jscockpit/blob/8.1.1/docs/installation/prep/Itsyou.online/configuration.md
