### ISSUE TITLE
verify owncloud installation

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays_jumpscale8#205]
related issue:
https://docs.greenitglobe.com/gig/proj_mauritius/issues/72

![screen shot 2017-03-17 at 11 29 51](https://cloud.githubusercontent.com/assets/8425762/24196367/353cc836-0f06-11e7-9078-7e5e667c9755.png)

**Comment by yveskerwyn** [comment]
@rkhamis, @daliusl as agreed I just ran it again, trying to reproduce.

I can confirm that the problem happens during the installations as you can clearly see in the below screenshot:

<img width="1612" alt="screen shot 2017-03-22 at 22 46 23" src="https://cloud.githubusercontent.com/assets/13795109/24215251/90d70800-0f51-11e7-8bb1-fa1bfc1a6838.png">

**Comment by khaledkbadr** [comment]
I can't reproduce the error. I made deployed new owncloud machine but the error did not appear. Is there any way I can reproduce this?

**Comment by yveskerwyn** [comment]
@khaledkbadr did you try on the Cockpit where I was able to reproduce?

**Comment by khaledkbadr** [comment]
@davshafik ran the blueprint from the Cockpit successfully. But when I ran the blueprint from Mauritius env, I found some weird `ays` related behavior regarding services execution

**Comment by yveskerwyn** [comment]
Thanks for your feedback @khaledkbadr, please continue doing your test on the Cockpit in Mauritius, nowhere else, since it's there that it will run, and we need it be perfectly running since on Sunday, time is clicking away for the launch of the Mauritius Cloud next week...

**Comment by khaledkbadr** [comment]
I think the problem with owncloud database creation is that we create a user `admin` and in the screenshot it tries to add privileges to user called `oc_admin` which does not exist. I created an issue on the owncloud repo to ask about this weird behavior 

https://github.com/owncloud/core/issues/27499

**Comment by khaledkbadr** [comment]
`This should work if you use a user that has no privilege to create a db.` This was owncloud developer response which does not make any sense. I believe this is a bug we shouldn't put too much effort into.
Anyway this issue does not affect `owncloud ` functionality
