### ISSUE TITLE
Can't run a destroyed succeeded repo

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#210]
**Steps**
- Create repo
- Add a blueprint
- Run this blueprint and make sure that it succeeded
![screenshot from 2017-03-26 15-47-51](https://cloud.githubusercontent.com/assets/17981089/24331837/7ed2dd4e-123c-11e7-8241-6af2002e3b47.png)
- Access the repo folder in the cockpit machine
- Run ays destroy, ays blueprint and ays run
- Check the created folders

**Actual result**
![screenshot from 2017-03-26 15-49-20](https://cloud.githubusercontent.com/assets/17981089/24331847/c4905726-123c-11e7-9f30-3c262c6dd8cd.png)

**Expected result**
Services should be created when user run 'ays blueprint'

**Version**
8.1.1

**Comment by rkhamis** [comment]
Since the API server archives blueprints after executing them, there's nothing to execute here.
