### ISSUE TITLE
Unexpected error when accessing a destroyed repo

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#212]
**Steps**
- Browse any repo's blueprint page.
- Destroy this repo
- Refresh the blueprint page

**Actual Result**
![screenshot from 2017-03-27 11-24-02](https://cloud.githubusercontent.com/assets/17981089/24350208/10f80e94-12ea-11e7-9e30-5bea6cc7caa4.png)

**Expected Result**
Error page muse be handled according to user experience.

**Version**
8.1.1

**Comment by rkhamis** [comment]
Like I explained, a destroyed repo is no longer seen by the cockpit. The error could be nicer, but it should be an error.
