### ISSUE TITLE
Unexpected responce when manipulate the repo url

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#213]
**Description**
Unexpected responce when manipulate any repo url.

**Steps**
- Open any repo page
- Change the repo name in the url to any random name or change it to be {{}}

**Actual Result**
![screenshot from 2017-03-27 11-50-55](https://cloud.githubusercontent.com/assets/17981089/24350783/35a7af4a-12ec-11e7-9ec2-e6c634028dfa.png)

![screenshot from 2017-03-27 11-50-09](https://cloud.githubusercontent.com/assets/17981089/24350787/37da00d8-12ec-11e7-95da-7c6ac7a73be7.png)

**Expected result**
API shouldn't trust user inputs without verifying it.

**Version**
8.1.1

**Comment by rkhamis** [comment]
This is just wiki, it literally just prints the value in the url for the view.
So it doesn't actually exist. Nothing is trusted when it comes to actual operations.

@islamTaha12 is this still considered an issue?

**Comment by islamTaha12** [comment]
I think 'not exist' is the expected response

**Comment by ramezsaeed** [comment]
yes I can see its still an issue but with low priority.

**Comment by rkhamis** [comment]
@islamTaha12 please report these type of issues on the portal repo from here on
