### ISSUE TITLE
Create an existing repo doesn't produce an error

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#214]
**Description**
Create an existing repo doesn't produce an error. 

**Steps**
- Create 'test' repo
- Make sure that this repo is created
- Try to create another repo with the same name ('test')

**Actual result**
There is no error response and the new repo won't be created

**Expected result**
Error message which indicate that this repo is existing

**Version**
8.1.1

**Comment by rkhamis** [comment]
Verify on 8.2.0

**Comment by rkhamis** [comment]
Produces error
