### ISSUE TITLE
mvp-cockpit: vdc service should not have account in its schema

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays_jumpscale8#25]
Currently the vdc schema has an **account** attribute in its schema.

The **vdc** service consumes a **g8client** which also has the account information.

We should remove the **account** attribute from the **vdc** schema and always read information from the **g8client**

**Comment by rkhamis** [comment]
Part of https://github.com/Jumpscale/ays_jumpscale8/issues/56

**Comment by rkhamis** [comment]
Not good.
This means you'll have a different client even if your user has access to multiple accounts.
