### ISSUE TITLE
VDC Actor Template update for suspending a VDC

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#55]
Instead of adding a OVC API to suspend a VDC and all its resources, idea is to have the AYS VDC service instance to iterate through all VMs and simply pause them + removing access for all users  

Suggested approach:
- new schema attribute suspended: 'on'/'off'

Needs validation by engineering...

**Comment by yveskerwyn** [comment]
Also see #56

**Comment by yveskerwyn** [comment]
@rkhamis can you comment on this?

This was one of the committed features, but less urgent then al the others.

**Comment by yveskerwyn** [comment]
What need is a Cloud Broker API to disable a Cloud Space, like the one we have for Accounts: `POST /cloudbroker/account/disable` - not sure however what it exactly does...

For cloud spaces I would mean:
- Block all incoming and outgoing network traffic for that cloud space
- Block all cloud APIs for that cloud space
- Disable VDC Control Panel interactions

**Comment by grimpy** [comment]
@yveskerwyn sounds good to me but then we need to create a FR on OVC repo.

**Comment by yveskerwyn** [comment]
OK see: https://github.com/0-complexity/openvcloud/issues/753
