### ISSUE TITLE
new service template for autosnapshotting

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#60]
autosnapshotting:
  vdc = type:str parent:vdc
  startDate = type:str default:''
  endDate = type:str default:''
  snapshotInterval = type:str default:'2h'
  retention = type:str default:'5d'

Also see: #56

**Comment by FastGeert** [comment]
See spec: https://github.com/0-complexity/ays_vdc_automated_snapshots/blob/master/specs/vdc-automated-snapshots.md
