### ISSUE TITLE
AYS service template for an OVC account

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#61]
Overlaps with g8client?

**Comment by rkhamis** [comment]
I don't see the added value of such an actor. Am I missing something?

**Comment by yveskerwyn** [comment]
@rkhamis, the added value is that you can use this to create a new G8 account, this would actually be a nice one for me to create as an exercise, makes sense

**Comment by yveskerwyn** [comment]
Please add documentation in a README.md during validation
