### ISSUE TITLE
ovc_user doesn't support itsyou.online users any more

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#68]
There used to be following implementation:
https://github.com/Jumpscale/ays_jumpscale8/blob/archive/_ovc/ovc_user/actions.py

Also the schema needs to be updated again, currently it is "empty" https://github.com/Jumpscale/ays_jumpscale8/blob/master/ovc/uservdc/schema.hrd

We used to be able to create blueprints like this:
ovc_user__mike:
  g8.client.name: gig
  username: 'mike
  email: 'mike@gmail.com
  provider: 'itsyouonline'

Please have this again working, since it breaks Moehaha.com, the work CentriLogic and Artilium

**Comment by xmonader** [comment]
Fixed in this commit https://github.com/Jumpscale/ays_jumpscale8/commit/4c7d70433cdae20b0b78283c2e0cde93dbf100f8

So you can now do the following 
```yaml
g8client__maing8:
   url: 'gig.demo.greenitglobe.com'                                                                                                                                    
   login: '*****'                                                                                                                                                    
   password: '*****'                                                                                                                                                
   account: '****'    

uservdc__adminx5:
   password: 'rooter123'
   email: 'adminx5@fake.com' 
   provider: 'itsyouonline'
   g8client: 'maing8'
   groups: 
      - 'admin'
      - 'user'
      - 'level1'
      - 'level2'
      - 'level3'
      - 'ovs_admin'
      - 'finance'

vdc__testvdcuser2:
   location: 'be-conv-2'
   g8client: 'maing8'
   uservdc:
      - adminx5```

**Comment by rkhamis** [comment]
Seems the user doesn't get created in the system_users

![nouser](https://cloud.githubusercontent.com/assets/8425762/20173373/b718ad70-a741-11e6-8a03-e14cab44264b.jpg)

Also, schema seems to have "username" which is never used. Very confusing. Please remove.

And please add this example in the README of the service. We'll lose this in no time.

**Comment by yveskerwyn** [comment]
@xmonader, @rkhamis,

Also the uninstall didn't work

**Actions blueprint:**
![screen shot 2016-11-10 at 12 30 56](https://cloud.githubusercontent.com/assets/13795109/20175130/8d9fe260-a741-11e6-8b99-e175eb618209.png)

**Service state:**
![screen shot 2016-11-10 at 12 31 33](https://cloud.githubusercontent.com/assets/13795109/20175149/a5fe1336-a741-11e6-9482-3b5823256273.png)

**Run details:**
![screen shot 2016-11-10 at 12 32 23](https://cloud.githubusercontent.com/assets/13795109/20175172/c0f36ad8-a741-11e6-9ec1-a87605169e11.png)

**More details:**

![screen shot 2016-11-10 at 12 39 52](https://cloud.githubusercontent.com/assets/13795109/20175420/eb30e2a2-a742-11e6-9b84-882eda6742b6.png)

**Comment by rkhamis** [comment]
logs are shown now

**Comment by yveskerwyn** [comment]
Problem is fixed, just verified
