### ISSUE TITLE
Services for importing/exporting VMs

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#70]
We need to create an AYS blueprint to do the description in https://github.com/0-complexity/openvcloud/blob/2.1/specs/import-export-virtual-machines.md

So please, set the missing services in this description and create services to allow us to test it.

**Comment by rkhamis** [comment]
Requires: https://github.com/Jumpscale/jumpscale_core8/issues/569

**Comment by grimpy** [comment]
For an export machine we should make a new services called `machine_export`
This service consumes a node.ovc and a owncloud. The default install action would peform the actual export.
Alternatily one can define this kind of service manully populating all the fields in the schema

node.ovc has an action import which can consume `machine_export` which basicly creates the node.ovc from the exported machine.

node.ovc actions install and import are mutually exclusive only one of the 2 can ever be called. A check should be written in the actions.

All  of these consumer/provider relations are purly optional.

**Comment by FastGeert** [comment]
Moving to roadmap. Good idea, but not critical or committed to a customer right now.

**Comment by zaibon** [comment]
the import/export are currently directly  implemented on the node.ovc service there. But I like the architecture proposed by @grimpy more.

**Comment by yveskerwyn** [comment]
And as discussed with @grimpy, agree with @FastGeert that we don't need (yet) an import/export actor template for customers now/today, but that is different for the OVS import/export API/features, those were committed to CentriLogic, they actually asked us about it yesterday, and they want to test it ASAP...

**Comment by zaibon** [comment]
If it's just about the OVC API it's done for weeks now.

**Comment by yveskerwyn** [comment]
correct @zaibon , and as a follow-up to yesterday's discussion, we need to review the API implementation, there were some ideas... feedback from customer was the S3 instead of webdav would be appreciated...

**Comment by xmonader** [comment]
https://github.com/Jumpscale/ays_jumpscale8/commit/d89564ec28de70f4506ad9844207adafe0f369da
