### ISSUE TITLE
mvp-cockpit: vdc actor doesn't set the capacity limits

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#74]
The current implementation of the VDC actor is very limited, not even good enough any more for demos, it provides less functionality than [the archived one](https://github.com/Jumpscale/ays_jumpscale8/blob/archive/_ovc/vdc/schema.hrd)

We need urgently need to implement the schema as requested here [#56](https://github.com/Jumpscale/ays_jumpscale8/issues/56)

**Comment by rkhamis** [comment]
Duplicate of https://github.com/Jumpscale/ays_jumpscale8/issues/56
