### ISSUE TITLE
Support spaces in the names of vdc and node.ovc actor templates 

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#78]
Currently both the actor template for vdc and node.ovc do not allow to create VDCs or VMs that contain spaces in their name because their names are set as follows:
```
vdc__$name_of_VDC$:
...
```

```
node.ovc__$name_of_VM$:
...
```

Is this a limitation in AYS?

How will we support spaces in the future?

**Comment by FastGeert** [comment]
Current version of AYS does not support spaces in names in this release.
