### ISSUE TITLE
example blueprint: kvm on packet.net with ubuntu 1604

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/ays_jumpscale8#81]
- in this repo, create /blueprintexamples/kvm_packet.net/
- put readme.md inside
- show 3 blueprints
   - how to put credentials of packet.net, define ssh key to be used
   - how to get 1 packet.net machine installed with ubuntu1604 and how to set sizes
   - how to create a VM for ubuntu inside kvm on this ubuntu 1604

- deliverables
   - full tutorial
   - VM with ubuntu can be accessed over internet

**Comment by delandtj** [comment]
only prob is that there is only one ip for the packet.net host, sou you'll have to use that host to nat TO the vm

**Comment by rkhamis** [comment]
https://github.com/Jumpscale/ays_jumpscale8/tree/8.1.0/examples/kvm_packet.net
