### ISSUE TITLE
Adding new actor template will not be loaded to AYS daemon/ays_api/portal

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/ays_jumpscale8#83]
steps: 
1- Add a new service 
2- Create a blueprint which is using this service
3- Send it using the Driver or using the following API
POST :  /ays/repository/{repository}/blueprint

Result:
Response : 400

**Comment by despiegk** [comment]
after adding a new template you have to reload the ays daemon, that is a know issue today
